FROM node:lts

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm install --save-dev @swc/cli @swc/core

RUN chmod -R 777 node_modules

ARG PORT=3000
ENV NODE_ENV=development

EXPOSE $PORT

CMD ["npm", "run", "start:dev"]
